In [13]:
import numpy as np
import random

In [3]:
X = np.array(([3,5], [5,1], [10,2], [11,1]), dtype=float)
y = np.array(([75], [82], [93], [90]), dtype=float)
X = X/np.amax(X, axis=0)
y = y/100 #Max test score is 100

In [14]:
x = np.array(([1,9],[3,8],[5,7],[9,6],[2,5],[4,4],[6,3],[8,2],[7,1]), dtype = float)
y1 = []
for i in range(0,len(x)):
    y1.append([(x[i,0] * x[i,1] + round(random.uniform(-3,3),0))/100])
x = x/ 10

In [4]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.yHat = self.forward(X)
        J = 0.5*sum((y-self.yHat)**2)
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)  
        
        return dJdW1, dJdW2

In [15]:
NN = Neural_Network()

In [6]:
cost1 = NN.costFunction(X,y)

In [48]:
dW1 , dW2 = NN.costFunctionPrime(X,y)

In [8]:
dW1

array([[ 0.0387677 ,  0.05733982,  0.00635487],
       [ 0.03649455,  0.0442242 ,  0.00485173]])

In [9]:
dW2

array([[-0.05636946],
       [-0.16389724],
       [-0.24705188]])

In [49]:
scalar = 3
NN.W1 = NN.W1 - scalar * dW1
NN.w2 = NN.W2 - scalar * dW2

In [38]:
cost2 = NN.costFunction(X,y)

In [7]:
print cost1, cost2

[ 0.36615797]

NameError: name 'cost2' is not defined

In [22]:
NN.forward(x)*100

array([[ 11.15862805],
       [ 21.63185076],
       [ 33.75070687],
       [ 54.24996518],
       [  7.98835917],
       [ 14.02169014],
       [ 16.70134025],
       [ 13.0427282 ],
       [  5.11883427]])

In [21]:
for i in range(0,100000):
    dW1 , dW2 = NN.costFunctionPrime(x,y1)
    scalar = 10
    NN.W1 = NN.W1 - scalar * dW1
    NN.W2 = NN.W2 - scalar * dW2

In [20]:
np.multiply(y1, 100)


array([[ 11.],
       [ 24.],
       [ 34.],
       [ 57.],
       [  8.],
       [ 17.],
       [ 16.],
       [ 15.],
       [  7.]])

In [23]:
x

array([[ 0.1,  0.9],
       [ 0.3,  0.8],
       [ 0.5,  0.7],
       [ 0.9,  0.6],
       [ 0.2,  0.5],
       [ 0.4,  0.4],
       [ 0.6,  0.3],
       [ 0.8,  0.2],
       [ 0.7,  0.1]])